---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      nodePort: 30007
      port: 80
      targetPort: 80
  type: NodePort