---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-beta
spec:
  selector:
    app: nginx-beta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-beta
spec:
  selector:
    matchLabels:
      app: nginx-beta
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-beta
    spec:
      containers:
      - name: nginx
        image: k-harbor-01.server.maas/library/nginx:latest
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: 
               - /bin/sh
               - -c
               - printf '<!DOCTYPE html><html><head><title>Welcome to nginx!</title></head><body><h1>BETA</h1></br><h1>Welcome to nginx!<br>%s </h1></body></html>' "${HOSTNAME}" > /usr/share/nginx/html/index.html
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-beta
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nginx-beta.username.play.k8s.maas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service-beta
            port:
              number: 80
